export const EMAIL_VERIFICATION_JOB = "EMAIL_VERIFICATION";
export const PASSWORD_RESET_JOB = "PASSWORD_RESET";
export const PHOTO_RETENTION_JOB = "PHOTO_RETENTION";

export const EMAIL_VERIFICATION_TTL_MS = 24 * 60 * 60 * 1000;
export const PASSWORD_RESET_TTL_MS = 60 * 60 * 1000;

export const MAX_PHOTO_BYTES = 8 * 1024 * 1024;
