export const SESSION_AUTO_OPEN_JOB = "SESSION_AUTO_OPEN";
export const SESSION_AUTO_CLOSE_JOB = "SESSION_AUTO_CLOSE";
export const ATTENDANCE_SHEETS_SYNC_JOB = "ATTENDANCE_SHEETS_SYNC";
export const MANUAL_CASE_EXPIRE_JOB = "MANUAL_CASE_EXPIRE";
